title: ''
labels: ['UI Component Request']
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to create a React Flow UI Component request! Please search open/closed requests before submitting, as the block or a similar one may have already been requested.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the functionality of the component in detail. Include images or similar examples if possible.
      placeholder: 'A color picker node which consist of a...'
    validations:
      required: true
